export const ListOfOrchids = [
  {
    id: "1",
    name: "Taichung Beauty",
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image: "https://barritaorchids.com/cdn/shop/products/Cf592_1024x1024.jpg",
    color: "pink",
    numberOfLike: 192,
    origin: "Taiwan",
    category: "Cattleya",
    clip: "https://www.youtube.com/embed/j77oX4c6IbM",
    info: "Taichung Beauty is a famous Cattleya hybrid from Taiwan known for its large pink blossoms and pleasant fragrance. It’s prized by collectors for its bright color and strong growth.",
  },
  {
    id: "2",
    name: "Phalaenopsis Aphrodite",
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image:
      "https://orchidroots.com/static/utils/images/species/spc_000055392_000151149.jpg",
    color: "white",
    numberOfLike: 85,
    origin: "Philippines",
    category: "Phalaenopsis",
    clip: "https://www.youtube.com/embed/PD_xsvVaUCU",
    info: "Phalaenopsis Aphrodite is a pure white moth orchid native to the Philippines, famous for its long-lasting blooms and graceful form. It inspired many modern hybrid varieties.",
  },
  {
    id: "3",
    name: "Vanda Coerulea",
    rating: 5,
    isSpecial: true,
    isNatural: true,
    image:
      "https://static.wixstatic.com/media/356cdc_181a53d8f2b64b8488cbd3e6073cc0a7~mv2.jpg/v1/fill/w_394,h_394,al_c,q_80,usm_1.20_1.00_0.01,enc_avif,quality_auto/Dendrobium%20Capituliflorum.jpg",
    color: "blue",
    numberOfLike: 230,
    origin: "India",
    category: "Vanda",
    clip: "https://www.youtube.com/embed/0k-qCyQtTQQ",
    info: "Vanda Coerulea, also called the Blue Vanda, is native to India and admired for its rare blue-purple tones. It thrives in bright light and warm humid environments.",
  },
  {
    id: "4",
    name: "Cymbidium Golden Elf",
    rating: 4,
    isSpecial: false,
    isNatural: false,
    image:
      "https://orchidroots.com/static/utils/images/hybrid/hyb_000151428_100061098.jpg",
    color: "yellow",
    numberOfLike: 64,
    origin: "Australia",
    category: "Cymbidium",
    clip: "https://www.youtube.com/embed/aSXpwVrcDro",
    info: "Cymbidium Golden Elf is a compact hybrid from Australia producing lemon-yellow, sweetly fragrant flowers. It’s well known for its ability to bloom in warmer climates.",
  },
  {
    id: "5",
    name: "Dendrobium Nobile",
    rating: 3,
    isSpecial: false,
    isNatural: true,
    image: "https://cdn.mos.cms.futurecdn.net/CCxdrRJ42XSs3fFFJDd63j.jpg",
    color: "purple",
    numberOfLike: 41,
    origin: "Thailand",
    category: "Dendrobium",
    clip: "https://www.youtube.com/embed/kXSqoObjkTs",
    info: "Dendrobium Nobile is a species orchid from Southeast Asia that produces clusters of purple-white flowers along its canes, often fragrant and long-lasting.",
  },
  {
    id: "6",
    name: "Miltonia Sunset",
    rating: 4,
    isSpecial: true,
    isNatural: false,
    image:
      "https://api.floriday.io/images/425f44d7-8f74-4ed7-bb8d-942fffcd2390.jpg",
    color: "red",
    numberOfLike: 73,
    origin: "Brazil",
    category: "Miltonia",
    clip: "https://www.youtube.com/embed/oQm-RSFmdyM",
    info: "Miltonia Sunset is a vibrant hybrid with red and orange shades that resemble a tropical sunset. It’s loved for its flat, open flowers and mild fragrance.",
  },
  {
    id: "7",
    name: "Oncidium Sharry Baby",
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image:
      "https://www.redfoxorchids.com.au/assets/full/P-1203.jpg?20211224113520",
    color: "brown",
    numberOfLike: 188,
    origin: "Ecuador",
    category: "Oncidium",
    clip: "https://www.youtube.com/embed/7xNNdnaUmYU",
    info: "Oncidium Sharry Baby, nicknamed the Chocolate Orchid, releases a delightful chocolate scent. It has long sprays filled with small maroon and white flowers.",
  },
  {
    id: "8",
    name: "Paphiopedilum Maudiae",
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image:
      "https://orchidroots.com/static/utils/images/hybrid/hyb_000152747_100041170.jpg",
    color: "green",
    numberOfLike: 59,
    origin: "Vietnam",
    category: "Paphiopedilum",
    clip: "https://www.youtube.com/embed/mN2KWsHrjOg",
    info: "Paphiopedilum Maudiae is a slipper orchid with elegant green and white striped petals. It’s easy to grow and blooms well in moderate indoor light.",
  },
  {
    id: "9",
    name: "Cattleya Walkeriana",
    rating: 5,
    isSpecial: true,
    isNatural: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWV1PU1Zmp5w0KTRJBJCe2W_Bnq2Jz2DkK8w&s",
    color: "pink",
    numberOfLike: 121,
    origin: "Brazil",
    category: "Cattleya",
    clip: "https://www.youtube.com/embed/LQbJetcEbvc",
    info: "Cattleya Walkeriana is a compact Brazilian orchid prized for its fragrance and bright pink flowers. It blooms during spring and early summer.",
  },
  {
    id: "10",
    name: "Phalaenopsis Sogo Yukidian",
    rating: 4,
    isSpecial: false,
    isNatural: false,
    image:
      "https://whiteplainsorchids.com/wp-content/uploads/2020/03/20200322_175725-scaled.jpg",
    color: "white",
    numberOfLike: 96,
    origin: "Taiwan",
    category: "Phalaenopsis",
    clip: "https://www.youtube.com/embed/029I0JszXrw",
    info: "Phalaenopsis Sogo Yukidian is a popular white hybrid with very large, round flowers. It’s one of the most common orchids used for exhibitions and gifts.",
  },
  {
    id: "11",
    name: "Vanda Miss Joaquim",
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image:
      "https://wonderwall.sg/images/default-source/content/dam/wonderwall/images/2025/04/on-this-day-in-1981--the-vanda-miss-joaquim-was-declared-singapore-s-national-flower/bitd_vandamiss_rectangle.jpg?sfvrsn=1fb7c31e_1",
    color: "violet",
    numberOfLike: 210,
    origin: "Singapore",
    category: "Vanda",
    clip: "https://www.youtube.com/embed/nnw_-SgnxLg",
    info: "Vanda Miss Joaquim is the national flower of Singapore, a hybrid orchid known for its vibrant violet petals and ability to bloom throughout the year.",
  },
  {
    id: "12",
    name: "Cymbidium Winter Fire",
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image:
      "https://orchidroots.com/static/utils/images/hybrid/hyb_000350338_100073535.jpg",
    color: "orange",
    numberOfLike: 52,
    origin: "China",
    category: "Cymbidium",
    clip: "https://www.youtube.com/embed/J1Rolz7COFA",
    info: "Cymbidium Winter Fire is a bright orange cymbidium hybrid that flowers during the cooler months, adding warmth and color to winter gardens.",
  },
  {
    id: "13",
    name: "Dendrobium Stardust",
    rating: 3,
    isSpecial: false,
    isNatural: false,
    image:
      "https://orchidroots.com/static/utils/images/hybrid/hyb_100074574_000008452.jpg",
    color: "yellow",
    numberOfLike: 33,
    origin: "Japan",
    category: "Dendrobium",
    clip: "https://www.youtube.com/embed/wQlFyHCVw9s",
    info: "Dendrobium Stardust is a compact Japanese hybrid producing clusters of bright yellow flowers. It’s known for easy flowering under bright light.",
  },
  {
    id: "14",
    name: "Miltoniopsis Herralexandre",
    rating: 4,
    isSpecial: true,
    isNatural: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKeWGE6XMUWooAXBRiPwhOoBUolQvqbJ0dYQ&s",
    color: "magenta",
    numberOfLike: 77,
    origin: "Colombia",
    category: "Miltoniopsis",
    clip: "https://www.youtube.com/embed/p9Waqx25aRg",
    info: "Miltoniopsis Herralexandre, also called the Pansy Orchid, has striking magenta flowers with white patterns. It prefers cool temperatures and soft light.",
  },
  {
    id: "15",
    name: "Oncidium Twinkle",
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image:
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEirZbeFXZfuopSB5ToHl1pnaJ84jueGqmL3ebAtgIeNW7IGGd76CyZQ9UHrEfPMlbbkX3qoiiBcbcSUmz76MI1m0WGRGdR63fw74n5EqsEu3jkDioUk9HHHV5I_q8B0DVOIyHj8KxeahrY/s1600/35545523320_af904c1d94_b.jpg",
    color: "white",
    numberOfLike: 68,
    origin: "Peru",
    category: "Oncidium",
    clip: "https://www.youtube.com/embed/kNiP-Ftyzvs",
    info: "Oncidium Twinkle is a miniature orchid covered with tiny, sweetly fragrant white blossoms. It’s perfect for small spaces and indoor growing.",
  },
  {
    id: "16",
    name: "Paphiopedilum Rothschildianum",
    rating: 5,
    isSpecial: true,
    isNatural: true,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/3a/Paphiopedilum_rothschildianum_%2825834537567%29.jpg",
    color: "striped",
    numberOfLike: 245,
    origin: "Borneo",
    category: "Paphiopedilum",
    clip: "https://www.youtube.com/embed/yj069-bTISc",
    info: "Paphiopedilum Rothschildianum, known as the King of Slippers, is a rare Bornean species with bold striped petals. It’s highly valued by orchid collectors.",
  },
];
